App\Entity\Task:
  attributes:
    normalization_context:
      groups: ['task_read']
  collectionOperations:
    get:
      method: 'GET'
      security: 'is_granted("TASK_READ")'
    post:
      method: 'POST'
      security: 'is_granted("TASK_CREATE")'
      denormalization_context:
        groups: ['task_post']
      swagger_context:
        parameters:
          - in: body
            name: task
            description: The task to create
            schema:
              type: object
              required:
                - name
                - description
                - project
              properties:
                name:
                  type: string
                description:
                  type: string
                project:
                  type: string
  itemOperations:
    get:
      method: 'GET'
      security: 'is_granted("TASK_READ", object)'
    put:
      method: 'PUT'
      security: 'is_granted("TASK_UPDATE", object)'
      denormalization_context:
        groups: ['task_put']
      swagger_context:
        parameters:
          - in: body
            name: task
            description: The task to update
            schema:
              type: object
              required:
                - name
                - description
              properties:
                name:
                  type: string
                description:
                  type: string
    delete:
      method: 'DELETE'
      security: 'is_granted("TASK_DELETE", object)'